### ISSUE TITLE
Cannot use $ref with other keywords in the same object

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-schemablocks/blocks-json-schema#1]
In draft-7 JSON Schema, you cannot use `$ref` with other keywords. All other keywords in that object are ignored.

For example: 
https://github.com/ga4gh-schemablocks/blocks-json-schema/blob/e3d0e382cf245c544427c32b8633ab8cda70f624/src/yaml/Individual.yaml#L47-L53

In stead, wrap the object in an `allOf`, splitting the `$ref` and annotations and/or other keywords into separate subschemas.

**Comment by theisuru** [comment]
Something like this ?
https://github.com/ga4gh-schemablocks/blocks-json-schema/blob/6618757de2a71a512ed98c5190b0bf8918d373e5/src/yaml/Age.yaml#L12-L25

**Comment by mbaudis** [comment]
@Relequestual @theisuru  This is a bit awkward. There is a clear case to be made for `description` and `examples` to be either provided by the instance of the `$ref`. This is especially relevant for these very "prototype" prototypes (think `OntologyClass`) where the documentation of the use cases is highly relevant.

Probably the this could be solved by having am special structure á la:

```
age_class: 
  "$ref": https://schemablocks.org/schemas/ga4gh/OntologyClass.json 
  instance:
    description: | 
      The age of the subject (e.g. individual at the onset of a phenotype), 
      as Ontology_class. An example ontology here is HsapDv (Human 
      Developmental Stages). 
    examples: 
      - id: 'HsapDv:0000083'
        label: 'infant stage'
```

... in JSON Schema. I also wonder how this works with arrays, where the `$ref` is a child of `items`?
