### ISSUE TITLE
Metadata inside schema

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-schemablocks/blocks-json-schema#4]
In the original "blocks" format I had included some of relevant meta information about e.g. provenance and use of the respective schema. This information is then also parsed into the web representations (using YAML -> MD tool and then having the web views auto-generated through Github's Jekyll engine).

Can we have the metadata represented in the original version (e.g. example for [Ontology_term](https://github.com/ga4gh-schemablocks/blocks/blob/master/src/yaml/ontology_term.yaml)) in the {@JS} document, e.g. in an `annotation` attribute? I really would like to keep this all bundled in one document.

```
annotation:
  authors:
    - "GA4GH Metadata Task Team"
    - "@cmungall"
    - "@mcourtot"
    - "@mbaudis"
  provenance:
    - description: "Original GA4GH schema"
      url: 'https://github.com/ga4gh/ga4gh-schemas/blob/master/src/main/proto/ga4gh/common.proto#L152'
    - description: "additional discussions with @cmungall and phenopackets developers"
  used_by:
    - description: Phenopackets
      url: 'https://github.com/phenopackets/phenopacket-schema/blob/master/docs/ontologyclass.rst' 
    - description: "Progenetix data schema"
      url: "http://progenetix.org"
      notes: |
        The Progenetix cancer genome data repository uses a data structure aligned with the GA4GH object model and schema recommendations.
        The OntologyTerm construct is used to represent a variety of core data elements, such as diagnostic classifications, material provenance genotypic sex.
      examples:
        - data_use_conditions:
            id: "DUO:0000004"
            label: "no restriction"
        - biocharacteristics:
          - description: "classic cerebellar medulloblastoma"
            type:
              id: "ncit:C3222"
              label: "Medulloblastoma"
```

**Comment by Relequestual** [comment]
I agree we should preserve this data.
JSON Schema is rather permissive in terms of additional keywords, so we can copy this directly.
Maybe the attribute should be `$docs` > `meta` as opposed to `annotations` though, as annotations have a specific meaning within JSON Schema.

**Comment by mbaudis** [comment]
@Relequestual Like below? And you would use `$docs` because there is/will be a schema for the structure?

```
$docs:
  meta:
    authors:
      - "GA4GH Metadata Task Team"
      - "@cmungall"
      - "@mcourtot"
      - "@mbaudis"
    provenance:
      - description: "Original GA4GH schema"
        url: 'https://github.com/ga4gh/ga4gh-schemas/blob/master/src/main/proto/ga4gh/common.proto#L152'
      - description: "additional discussions with @cmungall and phenopackets developers"
    used_by:
      - description: Phenopackets
        url: 'https://github.com/phenopackets/phenopacket-schema/blob/master/docs/ontologyclass.rst' 
```
